name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m pytest -v tests

      - name: Build coverage file
        run: |
          pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=src tests/ | tee pytest-coverage.txt    

      - name: Add Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml

  update-coverage-on-readme:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Check out repo code
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # Allow GitHub token to push changes
          fetch-depth: 0  # Ensure full history for commits

      - name: Generate Pytest coverage comment
        id: coverageComment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          hide-comment: true
          pytest-coverage-path: ./pytest-coverage.txt

      - name: Debug Coverage Output
        run: |
          echo "Coverage HTML: '${{ steps.coverageComment.outputs.coverageHtml }}'"

      - name: Update Readme with Coverage Html
        run: |
          coverage_html="${{ steps.coverageComment.outputs.coverageHtml }}"
          awk -v var="$coverage_html" '
          /<!-- Pytest Coverage Comment:Begin -->/ {print; print var; found=1; next}
          /<!-- Pytest Coverage Comment:End -->/ {found=0}
          !found' README.md > temp.md && mv temp.md README.md

      - name: Commit & Push changes to Readme
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update README with coverage report" || echo "No changes to commit"
          git push
